#####################################
# Death Location Configuration File #
#####################################


# DESCRIPTION
# message shown to the dead player
#
# PLACEHOLDERS
# x, y, z:	$x, $y, $z
# world:	$w
# player:	$n
#
# EXAMPLE
# message: 'Poor $n, you died in $w at $x, $y, $z!'
#
auto-message: '[Death Location] You died at $x, $y, $z. Press F3 to view your current position.'


# DESCRIPTION
# color of the message
#
# VALUES
# BLACK, WHITE, GRAY, DARK_GRAY,
# BLUE, GREEN, RED, YELLOW, AQUA, GOLD,
# DARK_BLUE, DARK_GREEN, DARK_RED, DARK_AQUA, DARK_PURPLE, LIGHT_PURPLE
#
# EXAMPLE
# color: 'DARK_PURPLE'
#
auto-color: 'DARK_RED'


# DESCRIPTION
# message shown to the command executing player
#
# PLACEHOLDERS
# x, y, z:	$x, $y, $z
# world:	$w
# player:	$n
#
# EXAMPLE
# message: 'Hi $n, you died in $w at $x, $y, $z!'
#
cmd-message: '[Death Location] You died at $x, $y, $z.'

# DESCRIPTION
# color of the message
#
# VALUES
# BLACK, WHITE, GRAY, DARK_GRAY,
# BLUE, GREEN, RED, YELLOW, AQUA, GOLD,
# DARK_BLUE, DARK_GREEN, DARK_RED, DARK_AQUA, DARK_PURPLE, LIGHT_PURPLE
#
# EXAMPLE
# color: 'DARK_PURPLE'
#
cmd-color: 'DARK_RED'
