#####################################
# Death Position Configuration File #
#####################################


# DESCRIPTION
# message shown to the dead player
#
# PLACEHOLDERS
# x, y, z:	$x, $y, $z
# world:	$w
# player:	$n
#
# EXAMPLE
# message: Poor $n, you died in $w at $x, $y, $z!
#
message: [Death Location] You died at $x, $y, $z


# DESCRIPTION
# color of the death message
#
# VALUES
# black, white, gray, dark gray,
# blue, green, red, yellow, aqua, gold,
# dark blue, dark green, dark red, dark aqua, dark purple, light purple
#
# EXAMPLE
# color: dark purple
#
color: dark red
