#####################################
# Death Position Configuration File #
#####################################

# DESCRIPTION
# message shown to the dead player
#
# PLACEHOLDERS
# x, y, z:	$x, $y, $z
# world:	$w
# player:	$n
#
# EXAMPLE
# message: Poor $n, you died in $w at $x, $y, $z!
#
message: $n, you died at $x, $y, $z
