#####################################
# Death Position Configuration File #
#####################################


# message shown to the dead player
#
# PLACEHOLDERS
# x, y, z:	$x, $y, $z
# world:	$w
#
# EXAMPLE
# message: Oh dear, you died in $w at $x, $y, $z
#
message: You died at $x, $y, $z
