name: Death Location
main: mrlawrence.bukkit.deathlocation.DeathLocation
version: 1.0.1
author: Mr. Lawrence

permissions:
  deathlocation.*:
    description: Gives access to everything
    children:
      deathlocation.automsg: true

  deathlocation.automsg:
    description: sends a message with coordinates on death
    default: true
