name: Death Location
main: mrlawrence.bukkit.deathlocation.DeathLocation
version: 1.1.1
author: Mr. Lawrence

permissions:
  deathlocation.*:
    description: Gives access to everything
    children:
      deathlocation.automsg: true

  deathlocation.automsg:
    description: sends a message with coordinates on death
    default: true

commands:
  mydeathloc:
    description: returns the last recorded death position of the player
    usage: /mydeathloc

